A_plus_Tsukuba/settings.py
board/admin.py
board/apis.py
board/models.py
board/serializers.py
board/urls.py
board/views.py
requirements.txt

get_subthreadsとget_repliesのAPIを実装しました。

Task 813 b2

---

board/static/board/about.css
board/static/board/common.css
board/templates/board/About.html
board/templates/board/Search.html

#21  
* コードの煩雑さを解消した  
* コードの記述量を削減した

直書きしていたstyleをBootstrapのクラス名やcssファイルに記述した。

---

board/templates/col7.html

add user-text class at sender_name #31

---

board/static/board/search.css
board/static/board/search.js
board/templates/board/Search.html

- Vue3で動作するように変更
- `*.prod.js`でも動作します
- イベント機構をシンプルにして、動作も軽快になりました
-  `style`を直接書いている場所が数か所残っていますが、CSS化するのは再利用性のメリットがあるときに限ったほうがいいかなと思いそのままにしています。みんなの意見が聞きたいです。

/search/のリファクタリング (issue #19

---

board/static/board/search.css
board/templates/board/Search.html
board/templates/col5.html

9 16 searchcard

---

board/models.py
init/README_MySQL.md
init/kdb2db_mysql.py

- `models.py`を変更しています。
　 - `schools`カラムの`max_length`がおかしかったのを修正
　 - `internal_id`を`AutoFiled`に変更
　 - `AutoFileld`に対して`default=0`を設定するとMySQLではエラーに案るので修正
- MySQL版の`kdb2db_mysql.py`を作成しました。
本番環境でテスト済みです。
本番DBには既にデータが注入してあります。

DB移行のための変更

---

A_plus_Tsukuba/settings.py
board/templates/board/Search.html
requirements.txt

`settings.py`に`local_settings.py`の有無で開発環境と本番環境を切り替えられるようにした。  
また、リモートサーバーの`deploy.sh`に`.env`ファイルをコピーするコマンドみ記述した。

本番環境用の設定を行った

---

board/templates/board/Search.html
board/views.py

920 search

---

board/apis.py
board/static/board/search.css
board/templates/board/Search.html
board/views.py

学群ごとの雑談スレッドへのリンクと検索の仕方を追加した

---

board/static/board/ITFchk.js

適度なタイミングでデプロイしてネタとして投下します
#51 参照

ITF警察への対応　(issue #51

---

board/templates/board/Search.html

学園祭スレッドの追加　(issue #55

---

board/admin.py

admin画面のカスタマイズ。検索ボックスや絞り込み条件を追加した。 #64

---

board/templates/board/Search.html

新入生スレッドの追加とリンクの追加

---

board/static/board/get_app.js
board/templates/board/App.html

iOSユーザーに優しく

---

board/templates/board/Search.html

スポンサーページの作成

---

board/static/board/ITFchk.js

ITFチェック遷移先をaboutにし、aboutでチェックを無効にする

---

.env_local
board/models.py
docker-compose.yml

年度更新メンテ用１(DB設定変更まで)

---

board/models.py
board/serializers.py
board/static/board/col7.js
board/static/board/send.js
board/templates/send.html

Ref twitterbot

---

board/templates/board/About.html

Aboutページにmeta descriptionを追加する

---

board/admin.py
board/models.py

Dev add review table

---

board/templates/board/Search.html

[fix] 全学計算機のリンクを修正

---

A_plus_Tsukuba/settings.py
board/templates/col7.html
board/views.py

これによりユーザーは投稿したフォームが正しく処理されていることを確認できる

投稿時にフラッシュメッセージを表示する

---

board/static/board/send.js
board/templates/send.html

https://github.com/half-blue/A_plus_Tsukuba/pull/121
ランクに応じて感情表示を変えた

Switch rank

---

board/static/board/share.css
board/templates/board/Search.html
board/templates/col5.html

Goodbye twitter, Hello X.

---

board/templates/board/Search.html

雑談スレッドへのモーダルを変更（学園祭ボタンを追加）

---

board/apis.py
board/serializers.py
board/urls.py

仕様等についてはこちらを確認してください。
https://github.com/half-blue/A_plus_Tsukuba/wiki/Review-API-(%E5%A4%96%E9%83%A8%E9%96%8B%E7%99%BA%E8%80%85%E5%90%91%E3%81%91%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E6%83%85%E5%A0%B1%E5%8F%96%E5%BE%97API)

レビュー情報APIの開発

---

board/templates/board/Search.html
board/templates/load_javascript.html

https://github.com/half-blue/aplus_mobile_flutter/issues/2
iOS実機で確認済み

スマホネイティブの時はITFチェックを通過する

---

board/static/board/advertise.js
board/static/board/search.js
board/templates/board/Chat.html
board/templates/board/Search.html
board/templates/col5.html

Allow cal x ama

---

docker-compose.yml

Add: 外部ネットワークの追加

---

board/templates/board/Search.html

add: 関東鉄道を追加

---

board/static/board/search.js
board/templates/board/Search.html

ユーザがアクセスする本体で宣伝する方が効果的であると考えたため

モバイルアプリの宣伝をA+つくば本体で行う

---

board/static/board/search.js
board/templates/board/Search.html

ref:https://github.com/half-blue/A_plus_Tsukuba/commit/0db1b43e056a084274d1057507c29e41b3cc4660

アップデートの促しコメントを削除

---

board/templates/board/Search.html

教室情報へのリンクを便利リンク集に追加する

---

board/views.py

fix #156 
`board/view.py`の55行目
```python
context["review_is_enable"] = thread.enable_review
```
を
```python
context["review_is_enable"] = True
```
とすると、フロントエンドの制限を解除でき、このPRの動作を検証できる。
レビュー禁止スレッドではHTTP 405が返る

レビューが許可されていないスレッドへのレビューをバックエンドで禁止する
